### ISSUE TITLE
[BUG] Today's wallpaper could not be displayed.

### ISSUE THREAD

**Issue by realasking** [Nriver/xfce-bing-wallpaper-everyday#1]
Dear author,
I have used your script for several days. It worked extremely well previously. However, some troubles have been met today, whereas a blank desktop was shown when the xfce was rebooted. I've checked your script, the command, the picture name, and found the problem comes with the quotation marks. The script doesn't escape quotation marks, but which were used in today's picture name.
At last, I think a simple fix would solve this problem,
just change line 26 from:
```return image_path```
to:
```return image_path.replace("\"","\\\"")```
Best regards~

**Comment by Nriver** [comment]
Thank you. Fixed in c2bddcb360fca6370ad282c312af437cf3a3c9d1
